### ISSUE TITLE
Can I hide background

### ISSUE THREAD

**Issue by hern12** [marconsou/mp-tick-bar#10]
Hi I cannot find setting about hide black blackground 
![image](https://github.com/marconsou/mp-tick-bar/assets/13413078/70e5f432-27f7-4ae8-8e92-70867a8b0825)
any suggestion thank you so much

**Comment by marconsou** [comment]
![Config](https://github.com/marconsou/mp-tick-bar/assets/27457164/7db78477-db3e-44ea-b27f-5300d70f7c48)

**Comment by hern12** [comment]
ah my eye thank you so much. Im not sure what I was config when I click lock it disappear but after I reset everything to default and click lock it work
