### ISSUE TITLE
Not seeing any visible changes?

### ISSUE THREAD

**Issue by SkylerMews** [marconsou/mp-tick-bar#2]
I would love to have a tool like this in my toolbelt, but unfortunately it doesn't seem to work for me (visually).

The ImGUI windows seem to show fine, and the commands too, but nothing on my MP bar or Job Bar?

I've tried removing all plugins, and reinstalling this plugin, but still nothing? 

I'm currently using Material UI Black, 4k UI, and have all the options within the config set to "Visible"

![Screenshot_5](https://user-images.githubusercontent.com/38995283/142996689-86644634-de8b-4ec5-9a29-86252a496576.png)

**Comment by marconsou** [comment]
Are you using the latest version (**1.3.2.0**)?

When you go to General and uncheck **Locked** you will see a black window on screen, can you see the bar inside? If you set both **Offset** to 0, the bar should appear at top left of the black window.

You might try reset all config to default (there is a button at bottom of config window), or you can backup you config file (**MPTickBar.json**), then delete the current one (Close your game before doing this)

If not, i gonna ask you to send your **MPTickBar.json** config file.
And to just make sure your bar is not being rendered outside of your screen, go to your **dalamudUI.ini**, find **[Window][MP Tick Bar]** and send me the values there.

**dalamudUI.ini** Path: %AppData%\XIVLauncher
**MPTickBar.json** Path: %AppData%\XIVLauncher\pluginConfigs

**Comment by SkylerMews** [comment]
Aha! That did seem to be the issue (Rendering off screen)! I manually edited the values within the **dalamudUI.ini** and managed to get it back on my screen. However, I did notice, the default size of the window seems to be 32x32 which is REALLY small for me xD

I'm using a 4k screen, so 32x32 is basically impossible for me to see. But it's all fixed and working now!

**Comment by marconsou** [comment]
Good call, i gonna put a default size for that window when you open it for first time. Thank you.

**Comment by SkylerMews** [comment]
@marconsou And thank you for an amazing plugin and quick response! I really appreciate your work! ♥

**Comment by marconsou** [comment]
Thanks, no problem.
