### ISSUE TITLE
Possible to make this work on any job?

### ISSUE THREAD

**Issue by Electyctz** [marconsou/mp-tick-bar#3]
Don't know of any other plugin that does this while also looking good, would be really nice for some other jobs.

**Comment by marconsou** [comment]
So want to always show the UI while playing other jobs? 
I didn't design to work that way because MP Tick is very specific to BLM.

**Comment by Electyctz** [comment]
Basically yeah, to show the server tick, Useful for BRD for example with the new procs

**Comment by marconsou** [comment]
OK, i gonna take a look at it and as long as it doesn't break anything, i gonna put an option to "always show".

**Comment by Electyctz** [comment]
much appreciated!

**Comment by marconsou** [comment]
I'm doing some testing and what you need is when any DoT ticks the bar should be synced?

**Comment by Electyctz** [comment]
Yes, exactly!

**Comment by marconsou** [comment]
I did some test and sadly this gonna be hard to do. 
The DoT tick doesn't happen at same time of MP Tick (same for Lucid Dreaming regen, HP regen, etc.), they are all separated.
The game send a lot of data when you apply a DoT, and the hardest part is to figure out how to filter it to avoid conflict and eventually make the bar resets at correct DoT time.
I gonna try few more things and see what happens.

**Comment by marconsou** [comment]
I did more changes and figured out how to sync the DoT Tick and it "seems" to be working, but the procs will happen completely random. Unless i missing something, i don't think it is the desired functionality.
I recorded a video to show it:
https://user-images.githubusercontent.com/27457164/147156858-9245b641-8aa0-421e-8d99-6b42443a8352.mp4
If you want i can create a version and send to you (for testing)

**Comment by Electyctz** [comment]
Hm, I had no idea the procs work on a different kind of tick lol. I had the

**Comment by marconsou** [comment]
Yeah, no problem.
