### ISSUE TITLE
Progress Bar Visibility option

### ISSUE THREAD

**Issue by piastol** [marconsou/mp-tick-bar#4]
Hello,

please add a Visibility function for Progress Bar.

"Only under Umbra Ice"

**Comment by marconsou** [comment]
Yeah, I can add it.
![Untitled](https://user-images.githubusercontent.com/27457164/147405689-d9685664-221d-485b-977a-b562e63b08a3.png)
The condition will be any Umbral Ice stacks and this will apply to all UI elements (because it is inside General Tab).

**Comment by piastol** [comment]
yes , big thanks:-D
